name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: Install dependencies
        run: go mod download
      - name: Run build
        run: >-
          go build
          -o advent-of-code-2020
          -ldflags "-X main.Name=advent-of-code-2020 -X main.Version=${GITHUB_REF:10}"
          cmd/advent-of-code-2020/advent-of-code-2020.go
        env:
          GOOS: linux
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: advent-of-code-2020
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
